CREATE TABLE IF NOT EXISTS lists (
id INTEGER PRIMARY KEY UNIQUE,
name TEXT NOT NULL, u
sername TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tasks (
id INTEGER PRIMARY KEY,
text TEXT NOT NULL,
list_id INTEGER,
 completed INTEGER
 );
 CREATE TABLE IF NOT EXISTS users (
 username TEXT PRIMARY KEY,
 password TEXT NOT NULL
 );